---
title: "Practical Machine Learning - Project"
author: "Shaun"
date: "May 20, 2017"
output: html_document
---

## Download Data

```{r echo=TRUE}
suppressMessages(library(caret))
suppressMessages(library(randomForest))
suppressMessages(library(ggplot2))
suppressMessages(library(rattle))
suppressMessages(library(ModelMetrics))
suppressMessages(library(gbm))
suppressMessages(library(glmnet))
suppressMessages(library(Hmisc))
suppressMessages(library(pgmm))
suppressMessages(library(forecast))
suppressMessages(library(dplyr))
suppressMessages(library(lubridate))

#setwd("D:/GitRepository/coursera/practicalmachinelearning/PracticalMachineLearning")
setwd("C:/Repository/MachineLearning/PracticalMachineLearning")
# Downloading data into a created directory if the directory does not exist.
if (!dir.exists("./data/")){
  dir.create("./data/")
  download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", destfile = "./data/training.csv")
  download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", destfile = "./data/testing.csv")
}
# Reading in the downloaded data
testing <- read.csv("./data/testing.csv")
training <- read.csv("./data/training.csv")
```

## Data Cleaning

```{r echo=TRUE}
for(i in names(training)){
  training[which(training[,i] == "" | training[,i] == "#DIV/0!" | training[,i] == "NA"), i] <- NA
}
na_cols <- names(training[, apply(is.na(training), 2, all)])
training <- training[, !apply(is.na(training), 2, all)]

factor_cols <- c("user_name","new_window")
date_cols <- c("cvtd_timestamp")

training[, c(factor_cols,"classe")] <- lapply(training[, c(factor_cols,"classe")], factor)
training[, date_cols] <- dmy_hm(training[, date_cols])

num_cols <- which(!names(training) %in% c(factor_cols,date_cols,"classe"))
training[, num_cols] <- lapply(training[, num_cols], as.numeric)

testing[, factor_cols] <- lapply(testing[, factor_cols], factor)
testing[, date_cols] <- dmy_hm(testing[, date_cols])
testing[, num_cols] <- lapply(testing[, num_cols], as.numeric)

```

## Data Exploration
```{r echo=TRUE}
training_sub <- subset(training, select = -c(X,user_name,raw_timestamp_part_1,raw_timestamp_part_2,cvtd_timestamp,new_window,classe))
training_agg <- training_sub %>% group_by(num_window) %>% summarise_each(funs(mean(., na.rm = TRUE)))

#train <- right_join(training_agg, training, by = "num_window")
#train <- merge(training_agg, training, by = "num_window", all.x = TRUE)
train

```
